name: 'PR auto assign'

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened


jobs:
  # PR 오픈시 Author 자동 할당
  assign-pr-author:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: .github/configs/pr-auto-assign-author-config.yml

  # PR 오픈시 In Progress 라벨링
  assign-pr-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          configuration-path: .github/configs/pr-auto-assign-label-config.yml
